aws-amplify/discord-bot

- customHttp.yml
Adds security headers to CloudFront distribution for frontend
https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.html#example-security-headers
> feat: add security headers to CF distribution

- packages/builder/index.js
Fixes regex to not transform package imports with names like `discord.js` to `discord.cjs`. Previously regex was looking for the `.js` file extension to transform.
> fix(builder): import regex to not transform "discord.js"

- packages/support/package.json
- packages/support/readme.md
- packages/support/src/index.ts
- packages/support/src/secrets.ts
- packages/support/tsconfig.json
- packages/support/vite.config.ts
Migrates logic from Amplify hooks to a dedicated support package
- loads secrets from dotenv using vite-provided `loadEnv`
- gets secrets from SSM by prefix
- creates secrets in SSM from local dotenv
- adds `exists` helper
- adds `readJson` helper
> feat: add support package

- README.md
- package.json
- re-adds `packages` script
- modifies build to run `packages` build before `apps`
- re-orders getting-started steps to mitigate "DATABASE_URL env var not found" issue with app build
> fix: getting started steps and build script

- apps/bot/svelte.config.js
- moves loadEnvVars into its own function for documentation purposes
- load variables prefixed with `DATABASE_` (fixes prisma issue)
> fix: load DATABASE_URL with SvelteKit

- src/lib/discord/Bank.ts
- src/lib/discord/client.ts
- removes usage of `createBank` helper in favor of creating Discord command bank directly with manually imported commands
- NOTE: `createBank` helper takes a directory path and dynamically imports commands, but since we are no longer building the bot as a library the filenames are changed and the directory does not exist in `build/`
> fix: "command not found" after building, manually import commands

- .env.sample
- Dockerfile
- cdk/package.json
- cdk/src/stack.ts
- cdk/src/support.ts
- pnpm-lock.yaml
- src/lib/next-auth.ts
- svelte.config.js
- loads `VITE_`-prefixed environment variables for Docker build
- NOTE: these environment variables should be public-facing and _not_ "secret"
- changes `VITE_NEXTAUTH_SECRET` to `NEXTAUTH_SECRET`, corrects CDK stack
> fix: docker build env vars for Svelte-Kit (import.meta.env)

- src/lib/discord/index.ts
- src/server.ts
- tsconfig.json
removes re-export of `client.ts` from `src/lib/discord/index.ts`, fixes in-source testing with Vitest
In the snippet below, we'll notice the error is thrown from a file different from the file being tested. This is because Vitest does not do any tree shaking, therefore all modules will be run when using an index file that is re-exporting many others.
```
> p test
> @aws-amplify/discord-bot@0.5.0 test /Users/josef/Documents/projects/aws-amplify/amplify-discord-bots
> vitest
DEV  v0.12.10 /Users/josef/Documents/projects/aws-amplify/amplify-discord-bots
↓ src/lib/notifications.ts (1) [skipped]
❯ src/lib/discord/commands/contribute.ts (0)
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
FAIL …
```
> fix: vitest in-source testing, remove client re-export

- svelte.config.js
- adds `decodeURI` to file URL of project directory
> fix: loading env vars when parent directory has a space in it

- cdk/src/construct.ts
> fix: cloudfront should talk to origin over HTTP

- src/routes/api/webhooks/github-release.ts
*Description of changes:* If the github webhook fails, log the parsed json body of the error message.
> fix: logging parsed error body

- cdk/src/components/hey-amplify-app.ts
- src/routes/api/webhooks/github-release.ts
- tests/server.ts
- adds headers to CloudFront cache key to pass to origin (GitHub webhook sha header was being stripped from the request sent to the app)
- adds error messages to endpoint
- adds tests for invalid payload body (to account for application/x-www-url-encoded types)
> feat(cdk): add headers to cf cache key, pass to origin for webhook

- src/lib/discord/client.ts
- src/lib/discord/commands/thread.ts
- src/lib/discord/support.ts
fixes #179 
- adds two helpers `isHelpChannel` and `isThreadWithinHelpChannel`
- adds conditional to thread command handler to check if thread is within help channel 
> fix(bot): thread command to respond correctly outside help, ref #179

- .github/workflows/ci.yml
> chore: rename ci action to run-ci

- src/lib/discord/api.ts
- src/lib/next-auth.ts
- src/routes/api/auth/[...nextauth].ts
- nextAuth api routes are now in all caps
- also changing requests in `api.ts` to be all caps
> fix: changing next auth api routes to all caps  

- prisma/schema.prisma
- src/lib/discord/client.ts
- fixes behavior where participant (`DiscordUser`)'s record is remapped to the most recent question participation
- enforces uniqueness on Participation model to ensure question ID and participant ID are added once, and participants (i.e. `DiscordUser`'s can have participations across multiple questions)
> fix(bot): enforce uniqueness on question ID + participant ID

- prisma/schema.prisma
- src/lib/discord/client.ts
- src/lib/discord/commands/select-answer.ts
- links answers to their participation records
- adds participation records for owners (required to select an answer's participation record and capture point-in-time roles)
> fix(bot): track answer participation record, owner is a participant

- src/routes/profile/link.svelte
closes #238
- removes restrictions and redirect in favor of helpful messaging
> fix(app): do not restrict profile/link when not logged in with discord

- prisma/schema.prisma
- src/lib/discord/commands/admin.ts
Fixing invocation of `prisma.gitHubDiscussion.create` to only include fields in the schema. 
> fix: adding GitHub Discussion that matches schema

- packages/vite-plugin-server/src/vite-plugin-server.ts
- vite.config.ts
- adds support with `vite-plugin-server` to disable the server in dev mode, allows bot to be created in `hooks.ts` and prevents clashing ports
> feat(vite-plugin-server): allow disabled dev server

- .github/workflows/issues-pending-author.yml
- adds new GitHub Action to automatically remove the `pending-author` label when the author has responded
> feat: add action to remove pending-author label

- src/lib/discord/commands.ts
removes usage of `$env` in favor of `process.env` for Node client code
> fix(bot): remove usage of $env from sveltekit

- .github/workflows/create-release.yml
- .github/workflows/release.yml
- cdk/src/app-github-actions.ts
- packages/support/src/secrets.ts
- modifies IAM policy of assumed role to grant access to "setup" secrets (e.g. manually created Route53 Hosted Zone ID)
- modifies release pipeline to _always_ deploy to staging environment. This ensures all changes into prod are first rolled into staging. In the event the container fails to start, this will only impact the staging environment with an estimated downtime of 20m-2hrs
- adds `NEXTAUTH` to the list of approved secret prefixes in order for support CLI to create secrets from dotenv to AWS SSM
- adds additional inputs to `create-release` action: `prepatch`, `preminor`, `premajor`
> feat(actions): allow pre-semver version options, enable NEXTAUTH secrets to SSM, rolling release

- src/lib/github/apply-roles.ts
migrates usage of `import.meta.env.VITE_DISCORD_GUILD_ID` to use `guildId` from params
> chore(app): migrate applyRoles to use guildId from params

- src/hooks/index.ts
- src/lib/constants.ts
- src/routes/+layout.server.ts
- src/routes/api/switch-guild/+server.ts
sets guild cookie on first request. previously this cookie would only be set after the server switch. This change will make it so the cookie is set on first request to the site, mitigating issues related to loading server configuration for admin page
> fix(app): always set guild cookie on init

- src/lib/discord/client.ts
- src/lib/discord/commands/thread.ts
modifies Discord threading to trim at 90 characters of original message. Fixes issue where thread title would exceed the constraint of 100 characters, where we're including the thread prefix `? - ` (4 chars) and suffix `...` (3 chars)
> fix(bot): Discord thread titles have a max of 100 characters

- src/routes/questions/[id]/+page.svelte
Modifies "view in Discord" link to open in the Discord app client rather than the same tab over https
> feat(app): "view in discord" opens in discord app client

- src/lib/discord/commands/thread.ts
migrates `/thread` command handler to get the subcommand and use a switch statement on the subcommand
> chore(bot): improve thread handling

- .github/workflows/ci.yml
- .github/workflows/create-release.yml
- .github/workflows/release-env.yml
migrates https://github.com/pnpm/action-setup from `v2.2.2` to `v2` for `set-output` deprecation
> chore(actions): migrate to use setup-pnpm v2

- src/routes/+layout.svelte
hides "Link your GitHub Account" link in the profile panel ahead of launching the GitHub App
> fix(app): hide github link

- package.json
- pnpm-lock.yaml
- src/routes/questions/+page.svelte
closes #372 
closes #373 
- adds filter by question status (solved & unsolved)
- adds filter by question channel
- adds sort by title, channel name, status
- adds ASC, DESC sorting
https://user-images.githubusercontent.com/5033303/220797113-e41c4e46-8c34-44a4-b4fe-cae2bad24fd3.mov
> add filters and sorting to questions page

- prisma/migrations/20230302013830_question_tags/migration.sql
- prisma/schema.prisma
- src/lib/discord/client.ts
ref #370 
adds support in the discord bot client to collect and store tags on forum channel posts
> feat(bot): support forum channel tags on questions

- src/routes/dashboard/+page.server.ts
- src/routes/dashboard/+page.svelte
- src/routes/dashboard/components/FilterMenu.svelte
- src/routes/dashboard/helpers/filter-questions-by-channel.ts
- src/routes/dashboard/helpers/filter-questions-by-date-range.ts
- src/routes/dashboard/helpers/filter-questions-by-tag.ts
- src/routes/dashboard/helpers/filter-questions.ts
- src/routes/dashboard/helpers/filter.ts
- src/routes/dashboard/types.d.ts
enables filtering by forum channel post tags. this follows the functionality of the `/questions` page where tags are automatically filtered to _all_, and removing tag selections will return all questions without tags (i.e. those created from text channels)
> add tag filter to dashboard page

- src/lib/discord/commands/select-answer.ts
re-orders select-answers operations to update the thread title after setting it as `isSolved` in the database
there's currently an issue between `select-answer` and the `ThreadUpdate` event handler where the command changes the threads title before setting `isSolved=true` in the database. When the thread title is updated, `ThreadUpdate`'s event handler fires and the two write events are clashing:
> reorder select-answer's data operations, mitigates multiple db writes

- src/lib/discord/client.ts
modifies backfill behavior to fetch all thread messages during participation backfill to ensure we capture each message and their authors
> fetch all thread messages during backfill

- src/lib/github/create-octokit.ts
- src/lib/github/get-github-members.ts
patches behavior where a failure to get the GitHub auth token (in the event the env var is not set or is invalid) takes down the dashboard page 
> patch github auth error

- scripts/seed.ts
- fixes issue where seed script was not using the latest prisma client
- adds 1-5 tags to questions instead of just 1
> fix seed script for question tags

- src/routes/dashboard/QuestionFilterMenu.svelte
#441 
- adds "select all" button to dashboard dropdown filters
- fixes issue with label overflow when selecting multiple filters 
> add "select all" button to dashboard dropdown filters

- src/routes/dashboard/+page.svelte
- src/routes/dashboard/ChannelHealthTable.svelte
- src/routes/dashboard/ForumChannelTagHealthTable.svelte
- src/routes/dashboard/constants.ts
- src/routes/dashboard/helpers/get-health.ts
- src/routes/dashboard/types.d.ts
fixed an issue where changes made to the filters on the dashboard page will display new rows on the table without health highlighting
> fix dashboard health table highlighting on state change

- src/routes/dashboard/QuestionFilterMenu.svelte
fixes an issue where the frontend will error upon selecting "days"
> fix dashboard time period dropdown's "day" value to use TIME_PERIOD constant

- src/routes/dashboard/ChannelHealthTable.svelte
- src/routes/dashboard/ForumChannelTagHealthTable.svelte
fixes dashboard health highlight display. health was being calculated based off the percentage string (e.g. `"75%"`) rather than the percentage number (`75`)
> hotfix dashboard health display, use percentage number

- .github/workflows/ci.yml
- package.json
this is mostly to prepare for the introduction of Playwright for browser testing
- changes ci action to run `pnpm test`
- removes silent logging
- note: when `CI=true`, running `vitest` is the same as running `vitest run` locally. it will run and exit
> ci to run test npm script

- src/lib/auth/config.ts
aligns with usage doc https://authjs.dev/reference/sveltekit#usage
> auth.js to trust host

- cdk/src/components/hey-amplify-app.ts
Container is currently using `VITE_NEXTAUTH_URL` to replace in client code at buildtime, however there appears to be an issue at runtime where it is reading from the load balancer's address. This PR aims to resolve this issue by setting a NEXTAUTH_URL env var at runtime.
> container uses NEXTAUTH_URL env var

- package.json
- pnpm-lock.yaml
- svelte.config.js
Fixes
```
Refused to connect to 'https://discord.com/api/oauth2/authorize?scope=identify+email&response_type=code&client_id=855489740135464980&redirect_uri=https%3A%2F%2Fnext.bot.amplify.aws%2Fauth%2Fcallback%2Fdiscord&code_challenge=XXX&code_challenge_method=S256' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
```
By adding `'connect-src': ['self', 'https://discord.com'],` to the Svelte config
> allow connections to discord for auth, fixes CSP issue

- cdk/src/components/waf.ts
- Reduces RateLimit request limit from 1000 (per 5 minutes) to 500
- Adds RateLimitApi rule
- Adds rules to block the following requests:
- requests ending in `.sql`
- requests to `/wp-admin`
- requests to `/wp-content`
- requests to `/swagger`
> add rules to block requests for .sql, wp-*, etc.

- cdk/src/components/waf.ts
> fix waf rules

- .github/workflows/ci.yml
`@actions/setup-node` does not support corepack out-of-the-box
With the move to use `corepack` and lean on `package.json#packageManager` to resolve package manager versions, the provided caching from `@actions/setup-node` cannot find the pnpm executable.
This PR aims to cache pnpm's store manually.
> cache pnpm manually in order to use corepack

- .gitignore
- apps/discord-bot-frontend/.gitignore
fixes issue with docker build where `pnpm deploy` the build output of the app. this is because pnpm looks at the localized gitignore as a filter when copying to the target destination (i.e. `./out`)
> fix ignore pattern for pnpm deploy

- Dockerfile
> fix container start, copy scripts from deployed output
