.npmrc
CONTRIBUTING.md
README.md
amplify.yml
amplify/.config/project-config.json
amplify/backend/function/discordcommands/src/index.js
amplify/backend/function/discordcommands/src/package.json
amplify/backend/function/discordinteraction/src/index.js
amplify/backend/function/discordinteraction/src/package.json
package.json
packages/app/package.json
packages/app/src/pages/__layout.svelte
packages/aws-exports/package.json
packages/bank/package.json
packages/bank/src/index.js
packages/builder/package.json
packages/command-giverole/package.json
packages/command-giverole/src/index.js
packages/command-static/package.json
packages/discord/package.json
packages/discord/src/handleCommand.js
packages/discord/src/syncCommands.js
packages/handler-commands/index.js
packages/handler-commands/package.json
packages/handler-interact/index.js
packages/handler-interact/package.json
packages/vite-plugin-discord-bot-layer/index.js
packages/vite-plugin-discord-bot-layer/package.json
scripts/verdaccio.yaml

reference discussion: https://github.com/josefaidt/amplify-discord-bots/discussions/28

feat: hey-amplify name change

---

packages/deploy/.gitignore
packages/deploy/.npmignore
packages/deploy/README.md
packages/deploy/example/app.ts
packages/deploy/example/cdk.json
packages/deploy/example/package.json
packages/deploy/example/tsconfig.json
packages/deploy/package.json
packages/deploy/src/index.ts

Adds a CDK construct+example which deploys a containerized bot to Fargate behind an Application Load Balancer

[WIP] feat(deploy): Add Fargate service

---

packages/discord/src/commands/contribute.ts

feat(bot): add /contribute command

---

packages/cdk-construct/package.json
packages/cdk-construct/src/index.ts
packages/cdk-construct/src/stack.ts
packages/cdk-construct/tsconfig.json
packages/cdk-construct/vite.config.ts

- adds lib package to serve as a base CDK stack with secrets from SSM

feat: add base cdk construct

---

apps/bot/tsconfig.json
packages/discord/tsconfig.json
packages/tsconfig/base.json

fix: remove vite/importMeta ref from shared tsconfig

---

cdk/src/app.ts
cdk/src/constants.ts
cdk/src/stack-app.ts
cdk/src/stack-base.ts
cdk/src/stack-bot.ts
cdk/src/stack.ts
cdk/src/types.d.ts

chore(cdk): fix cyclic reference

---

README.md
cdk/package.json
package.json
packages/support/package.json

- marks all packages private
- adds `setup` command (not to be confused with `pnpm setup`)

chore: private packages, add setup command

---

CONTRIBUTING.md

docs: add architecture diagram to contributing guide

---

cdk/src/construct.ts

closes #121 
modifies CF settings to redirect viewers to HTTPS

feat(cdk): cloudfront to redirect to https, ref #121

---

.env.sample
cdk/src/stack.ts

- removes unused `DISCORD_AUTH_REDIRECT_URI` env var

chore: rm DISCORD_AUTH_REDIRECT_URI

---

docker-compose.yml

fix: docker compose port mapping 🙃

---

package.json
pnpm-lock.yaml

fix: add @types/cookie

---

cdk/src/stack.ts

fix(cdk): add github release webhook secrets to container

---

package.json

release: 0.7.2

---

src/routes/api/questions/list.ts

chore(app): add generic authorized endpoint

---

src/routes/restricted.svelte

feat(app): restricted page to return proper status codes

---

package.json

fix: eslint script

---

package.json

release: 0.7.3

---

.github/workflows/ci.yml

fix: ci to setup pnpm before caching

---

.github/workflows/ci.yml

feat: map ci secrets to env vars

---

tests/server.ts

chore(test): remove test for removed page

---

.github/workflows/ci.yml

chore: add NEXTAUTH_SECRET to CI action

---

package.json

release: 0.7.4

---

prisma/schema.prisma
src/lib/discord/client.ts

- links Questions and Configuration back to Guild
- creates Guild on init
- creates Guild on add

feat: guild to be primary entity

---

src/lib/next-auth.ts

- disables `signIn` page
- redirects `signOut` page to `/logout`

feat(app): disable default next-auth pages

---

src/routes/__layout.svelte
src/routes/questions/index.svelte
src/routes/questions/index.ts
src/styles/sidenav.css

feat(app): add sidenav

---

.github/workflows/ci.yml

fix(ci): add bot token

---

package.json
pnpm-lock.yaml
prisma/schema.prisma
src/lib/discord/Bank.ts
src/lib/discord/client.ts
src/lib/discord/commands/select-answer.ts
src/lib/discord/commands/thread.ts
src/lib/discord/is-admin-or-staff.ts
src/routes/api/webhooks/github-release.ts

closes #75 
closes #141 
- upgrades discord.js to 14.x
- adds button to select answers to questions
- allows question owner to select answer
- allows admins to select answers
- allows staff to select answers
- stores answer ID and content in the database
- adds answer to generated question pages

feat(bot): add ability to select an answer

---

.github/workflows/ci.yml

feat(ci): add github secrets

---

package.json

- runs `tsc --noEmit` on staged TypeScript files

feat: run tsc on staged files on commit

---

package.json
src/hooks.ts

feat(app): add support for general public API routes

---

package.json
patches/@aws-sdk__util-user-agent-node@3.127.0.patch
pnpm-lock.yaml

fix: patch aws package for cdk esm

---

Dockerfile
cdk/src/components/hey-amplify-app.ts
cdk/src/stack.ts
src/routes/profile/link.svelte

fix(infra): remove litestream in favor of cron backup

---

src/lib/discord/commands/admin.ts
src/lib/discord/commands/contribute.ts
src/lib/discord/commands/github.ts
src/lib/discord/commands/giverole.ts
src/lib/discord/commands/login.ts
src/lib/discord/commands/thread.ts

fix(test): remove placeholder unit tests from commands

---

package.json
pnpm-lock.yaml

fix: move svelte to dependencies

---

prisma/schema.prisma
src/hooks.ts
src/lib/constants.ts
src/lib/db.ts
src/lib/discord/client.ts
src/lib/discord/get-user-access.ts
src/lib/discord/is-admin-or-staff.ts
src/lib/next-auth.ts
src/routes/__error.svelte
src/routes/admin/index.svelte
src/routes/admin/index.ts
src/routes/api/admin/configure.ts
src/server.ts

- adds several models to database, modifies existing AccessLevels
- adds db init function to seed AccessLevels
- relates participants to questions
- captures participant roles at point of participation (enables historical references to staff, if staff were to be removed from a member)

feat: track participation in questions

---

src/lib/discord/commands/admin.ts
src/routes/api/p/color/[code].ts

Adding endpoint to retrieve role colors based on decimal value provided by discord 

feat: adding color endpoint

---

CONTRIBUTING.md

docs: update repo reference, architecture diagram

---

package.json
scripts/start.sh

chore: move prisma generate from npm:prepare to postinstall

---

.github/workflows/ci.yml
tests/setup/seed.ts

```
pnpm vitest run --silent
```

chore(ci): silent tests

---

src/lib/next-auth.ts

fix(app): remove mention of NextAuth from error messages

---

cdk/src/components/hey-amplify-app.ts
cdk/src/components/waf.ts

feat(infra): add WAF

---

cdk/src/components/hey-amplify-app.ts

fix(infra): litestream needs bucket path, region

---

package.json

release: 0.8.0-next.1

---

package.json
pnpm-lock.yaml

fix: remove stray workspace package

---

.github/workflows/ci.yml

- adds `--silent` to pnpm install
- runs `pnpm build:lib` to build packages

chore(ci): silent install output, build packages

---

src/server.ts
svelte.config.js

adds secure headers to express server
```js
app.use((req, res, next) => {
res.header('Strict-Transport-Security', 'max-age=31536000; includeSubDomains')
res.header('X-Frame-Options', 'SameOrigin')
res.header('X-XSS-Protection', '1; mode=block')
res.header('X-Content-Type-Options', 'nosniff')
res.header(
'Content-Security-Policy',
"font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data:; script-src 'self' 'unsafe-inline'; default-src 'self';"
)
next()
})
```

feat(app): add secure headers to server

---

src/app.html
svelte.config.js

fix(app): csp headers

---

package.json

chore: add docker compose npm script

---

src/lib/LoginButton.svelte

fix(app): login button to always use VITE_HOST as redirect

---

package.json

release: 0.8.0-next.2

---

cdk/src/components/hey-amplify-app.ts
cdk/src/components/waf.ts

chore(infra): add WAF to ELB

---

cdk/src/components/hey-amplify-app.ts

chore(infra): enable deletion protection on ALB

---

package.json
pnpm-lock.yaml
src/routes/api/p/color/[code]/+server.ts
tests/server.ts

fix(app): color code for svg fill

---

cdk/package.json
cdk/src/components/hey-amplify-app.ts
cdk/src/stack.ts
pnpm-lock.yaml

- specifies ingress & egress rules for public subnets
- enables access logs from ALB to S3

feat(infra): specify ingress/egress rules, alb access logs

---

package.json

release: 0.8.0-next.3

---

.github/ISSUE_TEMPLATE/bug.yml

- adds a new GitHub issue template for reporting bugs

feat: add issue template for bugs

---

.github/workflows/issues-pending-author.yml

fix: use string instead of env var in if block

---

.github/ISSUE_TEMPLATE/new-command.yml

closes #137
- adds a new GitHub issue template for requesting new commands

feat: add issue template for new commands

---

.github/workflows/release.yml

fix(actions): release-env to inherit secrets from chosen env

---

.github/workflows/create-release.yml

fix(actions): pre* semver to create with `next` preid

---

.github/workflows/ci.yml
.github/workflows/release-env.yml

fixes next-auth routes in deployments (by default redirects to localhost:3000)

fix(actions): add VITE_ env vars to release actions

---

.github/workflows/release.yml

fix(actions): valid workflow file

---

.github/workflows/release-env.yml

fix(actions): sequential release not to create GitHub release for next

---

src/routes/+layout.server.ts

- improves messaging and default guild ID handling for main layout server load

chore(app): improve messaging for guilds

---

src/lib/discord/client.ts

fix(bot): ensure updated message is within a help channel thread before attempting to update answer content

---

src/lib/discord/commands.ts

improves messaging for command handling aimed to improve debugging experience

chore(bot): improve logging for command handling

---

.github/workflows/codeql.yml

feat(actions): add codeql

---

src/lib/discord/api.ts

adds `.patch()` to support PATCH calls with Discord API

chore(bot): add PATCH to Discord API helper

---

.github/ISSUE_TEMPLATE/feature-request.yaml
.github/ISSUE_TEMPLATE/new-command.yaml

chore: input -> textarea for issue templates

---

Dockerfile

hotfix dockerfile for prisma

---

cdk/src/stack.ts

remove ec2 instance

---

src/routes/questions/+page.server.ts
src/routes/questions/+page.svelte

related #370 
enables filtering by tags on the questions page

add tag filter to question page

---

cdk/src/stack.ts

hotfix: add ec2

---

cdk/src/stack.ts

hotfix: add ssh ingress

---

cdk/src/components/support-box.ts
cdk/src/stack.ts

hotfix: patch infrastructure

---

cdk/src/components/support-box.ts
cdk/src/stack.ts

hotfix: infrastructure part 2

---

cdk/src/components/support-box.ts

hotfix: patch infrastructure round 3

---

cdk/src/components/support-box.ts

chore: require imdsv2 on ec2 instances

---

src/lib/discord/client.ts

captures updates to threads, including:
- Forum Channel posts' tags (added/removed)
- question title
- participation records (backfill if necessary)

feat: capture updates to threads (title, tags)

---

cdk/src/app.ts

enable termination protection for cfn stacks

---

cdk/src/components/waf.ts

raise WAF ratelimit to 1000rq/5m

---

cdk/src/stack.ts

limit connections to SQLite to 1

---

package.json
pnpm-lock.yaml
prisma/migrations/20230331205100_question_tags_unique_id_name/migration.sql
prisma/schema.prisma
src/lib/discord/client.ts

refactors `connectOrCreate` to mitigate issues with duplicate attempts of tag creation

fix: question update tag connectOrCreate, fixes select-answer

---

scripts/start.sh

rm db file check

---

src/lib/github/create-octokit.ts
src/lib/github/get-github-members.ts

patch github auth error

---

src/routes/dashboard/+page.svelte
src/routes/dashboard/QuestionBarChart.svelte
src/routes/dashboard/helpers/filter-answers.ts

#434 
- fixes an issue where selecting a frequency does not change the bar chart
- fixes an issue where selecting a different start/end date does not update data

fix date filter, bind start/end dates, fix frequency bar chart

---

src/routes/dashboard/+page.svelte
src/routes/dashboard/QuestionBarChart.svelte

disable csv download

---

cdk/package.json
cdk/src/components/privacy-notification-function/privacy-notification-function.ts
pnpm-lock.yaml

hotfix lambda handler entry path

---

cdk/cdk.json

fix cdk require approval

---

cdk/src/components/privacy-notification-function/handler.ts

allow decrypt on function ssm get parameter

fix: ssm decrypt

---

.github/workflows/ci.yml

- adds `DISCORD_GUILD_ID` to test step

ci test step uses DISCORD_GUILD_ID

---

cdk/src/components/hey-amplify-app.ts

SvelteKit to use ORIGIN env var

---

cdk/src/components/waf.ts

removes pseudo-header bytematch

fix waf rules 2

---

cdk/src/components/hey-amplify-app.ts
package.json
pnpm-lock.yaml

- support new X-header from auth.js (`x-auth-redirect-return`)
- upgrade auth.js lib

upgrade auth.js, add auth.js x-header

---

cdk/src/components/waf.ts

hotfix waf rules priority

---

.github/workflows/create-release.yml
.github/workflows/release-env.yml

change .nvmrc -> .node-version

---

.github/workflows/release-env.yml

build:lib -> build-lib

---

Dockerfile

this feature is nice when you're building locally, however is not required in a CI setting

make secret env mount not required

---

Dockerfile
apps/discord-bot-frontend/package.json

added playwright install at setup in package.json

---

Dockerfile

fix docker image build for sveltekit server

---

packages/support/package.json
pnpm-lock.yaml

upgrade vite

---

Dockerfile

fix docker build, remove COPY patches

---

cdk/src/components/waf.ts

split .tar.gz waf rule into two

---

Dockerfile

copy prisma to final build image

---

apps/discord-bot-frontend/package.json
apps/discord-bot-frontend/src/routes/+layout.server.ts
apps/discord-bot-frontend/src/routes/admin/+page.server.ts
apps/discord-bot-frontend/src/routes/admin/integrations/+page.server.ts
apps/discord-bot-frontend/src/routes/admin/integrations/[code]/+page.server.ts
apps/discord-bot-frontend/src/routes/api/admin/+layout.server.ts
pnpm-lock.yaml

fix: remove faker js from devDep

---

pnpm-lock.yaml

fix: resolve lockfile duplicate keys

---

apps/discord-bot-frontend/package.json
pnpm-lock.yaml

chore: dependabot fixes

---

CONTRIBUTING.md

added the code of conduct and security section

added the code of conduct and security section
